/**
 * Type Generator Utility
 *
 * Generates TypeScript definition files (`.d.ts`) for translation keys,
 * enabling IDE autocomplete and compile-time type checking when using
 * translation functions.
 *
 * @module utils/type-generator
 */

import { dirname } from "path";
import { writeFileSync, mkdirSync } from "fs";

import type { TranslationResources } from "@/interfaces";

/**
 * Generate and write a TypeScript definition file for translation keys.
 *
 * Collects every unique key across all languages and namespaces, then
 * emits a `.d.ts` file containing a `TranslationKey` union type and a
 * `translationKeys` map constant.
 *
 * @param resources - Translation resources object keyed by language → namespace → keys
 * @param outputPath - Absolute or relative path where the `.d.ts` file will be written
 * @param debug - When `true`, logs the number of generated keys to stdout
 * @returns Resolves when the file has been written
 *
 * @example
 * ```typescript
 * const resources = {
 *   en: {
 *     translation: {
 *       'greeting': 'Hello',
 *       'auth.login': 'Login'
 *     }
 *   }
 * };
 * await generateTypeDefinitions(resources, '.stackra-inc/react-i18n/types/index.d.ts');
 * ```
 */
export async function generateTypeDefinitions(
  resources: TranslationResources,
  outputPath: string,
  debug: boolean = false,
): Promise<void> {
  const allKeys = new Set<string>();

  for (const language in resources) {
    if (Object.prototype.hasOwnProperty.call(resources, language)) {
      const namespaces = resources[language];

      for (const namespace in namespaces) {
        if (Object.prototype.hasOwnProperty.call(namespaces, namespace)) {
          const namespaceData = namespaces[namespace];
          if (namespaceData) {
            const keys = extractKeys(namespaceData);
            keys.forEach((k) => allKeys.add(k));
          }
        }
      }
    }
  }

  const typeDefinition = generateTypeDefinitionCode(Array.from(allKeys));

  const dir = dirname(outputPath);
  mkdirSync(dir, { recursive: true });

  writeFileSync(outputPath, typeDefinition, "utf-8");

  if (debug) {
    console.log(`[i18n] Generated type definitions with ${allKeys.size} keys at ${outputPath}`);
  }
}

/**
 * Extract all translation keys from a nested object using dot notation.
 *
 * Recursively walks the object tree, building dot-separated key paths
 * for every leaf value.
 *
 * @param obj - Object to extract keys from
 * @param prefix - Dot-notation prefix accumulated from parent keys
 * @returns Flat array of all keys in dot notation (e.g. `['auth.login', 'auth.logout']`)
 *
 * @example
 * ```typescript
 * extractKeys({ auth: { login: 'Login' } });
 * // => ['auth.login']
 * ```
 *
 * @internal
 */
function extractKeys(obj: Record<string, any>, prefix: string = ""): string[] {
  const keys: string[] = [];

  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) {
      const fullKey = prefix ? `${prefix}.${key}` : key;
      const value = obj[key];

      if (value !== null && typeof value === "object" && !Array.isArray(value)) {
        keys.push(...extractKeys(value, fullKey));
      } else {
        keys.push(fullKey);
      }
    }
  }

  return keys;
}

/**
 * Generate the TypeScript source code for the type definition file.
 *
 * Produces a `TranslationKey` union type and a `translationKeys` constant
 * map, both sorted alphabetically for deterministic output.
 *
 * @param keys - Flat array of all translation keys
 * @returns Complete `.d.ts` file content as a string
 *
 * @internal
 */
function generateTypeDefinitionCode(keys: string[]): string {
  const sortedKeys = keys.sort();

  const unionMembers = sortedKeys.map((k) => `  | "${k}"`);
  const mapEntries = sortedKeys.map((k) => `  "${k}": "${k}";`);

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file is generated by @stackra/react-i18n
 * Contains type definitions for all translation keys
 */

/**
 * Union type of all available translation keys
 * Use this for type-safe translation key selection
 */
export type TranslationKey =
${unionMembers.join("\n")};

/**
 * Map of all available translation keys
 * Useful for programmatic access to translation keys
 */
export declare const translationKeys: {
${mapEntries.join("\n")}
};
`;
}
