/**
 * Virtual Module Generator
 *
 * Produces the TypeScript source code for the Vite virtual module
 * `virtual:@stackra/react-i18n`. The generated code initializes i18next,
 * registers plugins (HTTP backend, language detector), and exports
 * translation helper functions.
 *
 * @module utils/virtual-module-generator
 */

import type { I18nextConfig } from '@/interfaces';

/**
 * Generate the virtual module source code.
 *
 * Serializes the provided i18next configuration into a self-contained
 * TypeScript module that can be resolved by Vite's virtual module system.
 * The generated module exports `__`, `t`, `trans`, `i18next`,
 * `changeLanguage`, `getLanguage`, `getLanguages`, and `addResources`.
 *
 * @param config - Complete i18next configuration (including resources)
 * @returns TypeScript source code as a string, ready to be served by Vite
 *
 * @example
 * ```typescript
 * const code = generateVirtualModule(config);
 * // Returns a string of TypeScript that Vite resolves as
 * // 'virtual:@stackra/react-i18n'
 * ```
 */
export function generateVirtualModule(config: I18nextConfig): string {
  const configJson = JSON.stringify(config, null, 2);

  return `
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file is generated by @stackra/react-i18n Vite plugin
 * It exports translation functions and the i18next instance
 */

import i18next from 'i18next';
import HttpBackend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { setupGlobalI18n } from '@stackra/react-i18n/utils/global-setup.util';

const i18nConfig = ${configJson};

if (i18nConfig.backend) {
  i18next.use(HttpBackend);
}

if (i18nConfig.detection) {
  i18next.use(LanguageDetector);
}

if (!i18next.isInitialized) {
  i18next.init(i18nConfig);
}

setupGlobalI18n();

/**
 * Simple translation function.
 *
 * @param key - The translation key to look up
 * @returns The translated string
 */
export const __ = (key: string): string => i18next.t(key);

/**
 * Main translation function with options.
 *
 * @param key - The translation key to look up
 * @param options - Optional i18next options (interpolation, etc.)
 * @returns The translated string
 */
export const t = (key: string, options?: Record<string, any>): string =>
  options ? i18next.t(key, options) : i18next.t(key);

/**
 * Alias for {@link t}.
 *
 * @param key - The translation key to look up
 * @param options - Optional i18next options
 * @returns The translated string
 */
export const trans = (key: string, options?: Record<string, any>): string =>
  t(key, options);

/**
 * The initialized i18next instance.
 * Provides full access to the i18next API.
 */
export { i18next };

/**
 * Change the current language.
 *
 * @param language - The language code to switch to
 * @returns Promise that resolves when the language change is complete
 */
export const changeLanguage = (language: string): Promise<string> =>
  i18next.changeLanguage(language);

/**
 * Get the currently active language.
 *
 * @returns The current language code
 */
export const getLanguage = (): string => i18next.language;

/**
 * Get all available languages.
 *
 * @returns Array of language codes
 */
export const getLanguages = (): string[] => i18nConfig.preload || [i18nConfig.lng || 'en'];

/**
 * Add translation resources at runtime.
 *
 * @param language - The language code
 * @param namespace - The namespace name
 * @param resources - The translation key-value pairs
 */
export const addResources = (language: string, namespace: string, resources: Record<string, any>): void => {
  i18next.addResources(language, namespace, resources);
};
`;
}
