/**
 * i18next Config Interface
 *
 * Extends the base {@link I18nextOptions} with the `resources` property
 * populated by the config builder after scanning translation files.
 *
 * @module interfaces/i18next-config
 */

import type { I18nextOptions } from "@/types";
import type { TranslationResources } from "./translation-resources.interface";

/**
 * Complete i18next configuration interface
 * Represents the full configuration that will be passed to i18next.init()
 * Combines all i18next options with the generated translation resources
 *
 * @see https://www.i18next.com/overview/configuration-options
 *
 * @example
 * ```typescript
 * const config: I18nextConfig = {
 *   lng: 'en',
 *   fallbackLng: 'en',
 *   ns: ['translation', 'common'],
 *   defaultNS: 'translation',
 *   resources: {
 *     en: {
 *       translation: { ... },
 *       common: { ... }
 *     },
 *     ar: {
 *       translation: { ... },
 *       common: { ... }
 *     }
 *   },
 *   interpolation: {
 *     escapeValue: false
 *   }
 * };
 * ```
 */
export interface I18nextConfig extends I18nextOptions {
  /**
   * Translation resources loaded from files
   * Contains all translations for all languages and namespaces
   * Generated by ConfigBuilder from discovered translation files
   *
   * @example
   * ```typescript
   * resources: {
   *   en: {
   *     translation: { 'key': 'value' },
   *     common: { 'button': 'Button' }
   *   }
   * }
   * ```
   */
  resources?: TranslationResources;
}
